apiVersion: v1 
kind: Service 
metadata: 
  name: grid-etcd-service 
  labels:
    provider: itfantasy
spec: 
  type: ClusterIP
  sessionAffinity: ClientIP
  ports: 
  - name: port-a
    port: 32379
    targetPort: 32379
    protocol: TCP
  - name: port-b
    port: 32380
    targetPort: 32380
    protocol: TCP
  selector: 
    tag: grid-etcd