appname: k8cluster
cluster: 
  namespace: itfantasy
  regdc: etcd://172.21.1.198:32379/gonode
  deployments:
  - name: proj-template
    num: 3
    endpoints:
    - tcp://:30005
    - kcp://:30006
    - ws://:30010/proj-template
    proj: proj-template
    backends: ""
    ispub: 1
    command: ""
    enable: 1
  statedeployments: 
  - name: statesvc
    num: 3
    startindex: 1
    endpoints:
    - tcp://:30100
    - kcp://:30200
    - ws://:30300/statesvc
    proj: statesvc
    backends: ""
    ispub: 1
    command: ""
    enable: 0