appname: k8scluster
cluster: 
  namespace: itfantasy
  deployments:
  - name: game
    num: 3
    endpoints:
    - tcp://:30005
    - kcp://:30006
    - ws://:30010/game
    proj: game
    command: ""
    enable: 1
  statedeployments: 
  - name: statesvc
    num: 3
    startindex: 1
    endpoints:
    - tcp://:30100
    - kcp://:30200
    - ws://:30300/statesvc
    proj: statesvc
    command: ""
    enable: 1