---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ##NAME##
spec:
  replicas: ##NUM##
  template:
    metadata:
      labels:
        app: ##APPNAME##
        tag: ##NAME##
        namespace: ##NAMESPACE##
        provider: itfantasy
    spec:
      containers:
      - name: ##NAME##-instance
        image: itfantasy/grid:latest
        command: ["etc/grid/grid-core", "-proj=/mnt/grid/runtime/##PROJ##"##COMMAND##]
        volumeMounts:
        - name: runtime-volume
          mountPath: /mnt/grid/runtime
        ports:
##PORTS##
        env:
        - name: GRID_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRID_NODE_NAME
          value: ##NAME##
        - name: GRID_NODE_ENDPOINTS
          value: "##ENDPOINTS##"
        - name: GRID_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRID_NODE_NAMESPACE
          value: ##NAMESPACE##
        - name: GRID_NODE_REGDC
          value: "##REGDC##"
        - name: GRID_NODE_BACKENDS
          value: "##BACKENDS##"
        - name: GRID_NODE_ISPUB
          value: "##ISPUB##"
      volumes:
      - name: runtime-volume
        persistentVolumeClaim:
          claimName: pvc-##APPNAME##