---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ##NAME##
spec:
  replicas: ##NUM##
  template:
    metadata:
      labels:
        app: ##APPNAME##
        engine: itfantasy-grid
        tag: ##NAME##
        namespace: ##NAMESPACE##
    spec:
      containers:
      - name: ##NAME##-instance
        image: itfantasy/grid
        command: ["etc/grid/grid-core", "-proj=/etc/grid/runtime"##COMMAND##]
        volumeMounts:
        - name: runtime-volume
          mountPath: /etc/grid/runtime
        ports:
##POINTS##
        env:
        - name: GRID_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRID_NODE_NAME
          value: ##NAME##
        - name: GRID_NODE_ENDPOINTS
          value: ##ENDPOINTS##
        - name: GRID_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRID_NODE_NAMESPACE
          value: ##NAMESPACE##
      volumes:
      - name: runtime-volume
        hostPath:
          path: ##RUNTIME##
          type: Directory