apiVersion: v1 
kind: Service 
metadata: 
  name: ##NAME##-service
  labels:
    provider: itfantasy
spec: 
  type: NodePort
  sessionAffinity: ClientIP
  ports: 
##PORTS##
  selector: 
    tag: ##NAME##