---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ##NAME##-##STATEINDEX##
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ##APPNAME##
        engine: itfantasy-grid
        tag: ##NAME##
        namespace: ##NAMESPACE##
        stateIndex: "##STATEINDEX##"
    spec:
      hostNetwork: true
      containers:
      - name: ##NAME##-instance
        image: itfantasy/grid:latest
        command: ["etc/grid/grid-core", "-proj=/mnt/grid/runtime/##NAME##"##COMMAND##]
        volumeMounts:
        - name: runtime-volume
          mountPath: /mnt/grid/runtime
        ports:
##POINTS##
        env:
        - name: GRID_NODE_ID
          value: ##NAME##-##STATEINDEX##
        - name: GRID_NODE_NAME
          value: ##NAME##
        - name: GRID_NODE_ENDPOINTS
          value: "##ENDPOINTS##"
        - name: GRID_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRID_NODE_NAMESPACE
          value: ##NAMESPACE##
      volumes:
      - name: runtime-volume
        persistentVolumeClaim:
          claimName: pvc-##APPNAME##