---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ##NAME##
spec:
  replicas: ##NUM##
  template:
    metadata:
      labels:
        app: ##APPNAME##
        engine: itfantasy-grid
        tag: ##NAME##
    spec:
      containers:
      - name: ##NAME##-instance
        image: itfantasy/grid
        command: ["etc/grid/grid", "-d=/etc/grid/runtime"##COMMAND##]
        volumeMounts:
        - name: runtime-volume
          mountPath: /etc/grid/runtime
        ports:
        - containerPort: ##PORT##
        env:
        - name: GRID_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRID_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRID_NODE_LABEL
          value: ##NAME##
        - name: GRID_NODE_PORT
          value: "##PORT##"
        - name: GRID_NODE_PROTO
          value: ##PROTO##
      volumes:
      - name: runtime-volume
        hostPath:
          path: ##RUNTIME##
          type: Directory